// Convenience re-export so widgets can write:
//   import '/l10n/l10n.dart';
//   AppLocalizations.of(context)!.profileTitle
//
// The AppLocalizations class itself is generated by `flutter gen-l10n`
// (triggered automatically when `generate: true` is set in pubspec.yaml).
export 'package:aarogyam/l10n/app_localizations.dart';
