import '/flutter_flow/flutter_flow_theme.dart';
import '/flutter_flow/flutter_flow_util.dart';
import 'package:google_fonts/google_fonts.dart';
import 'a_i_disclaimer_model.dart';
export 'a_i_disclaimer_model.dart';

class AIDisclaimerWidget extends StatefulWidget {
  /// I need a component for disclaimer for users: DO NOT COMPLETELY RELY ON THE
  /// AI GENERATED CONTENT, YOU MUST CONSULT A DOCTOR.
  const AIDisclaimerWidget({super.key});

  @override
  State<AIDisclaimerWidget> createState() => _AIDisclaimerWidgetState();
}

class _AIDisclaimerWidgetState extends State<AIDisclaimerWidget>
    with RouteAware {
  late AIDisclaimerModel _model;

  @override
  void setState(VoidCallback callback) {
    super.setState(callback);
    _model.onUpdate();
  }

  @override
  void initState() {
    super.initState();
    _model = createModel(context, () => AIDisclaimerModel());
  }

  @override
  void dispose() {
    _model.maybeDispose();

    super.dispose();
  }

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    final route = DebugModalRoute.of(context);
    if (route != null) {
      routeObserver.subscribe(this, route);
    }
    debugLogGlobalProperty(context);
  }

  @override
  void didPopNext() {
    if (mounted) {
      setState(() => _model.isRouteVisible = true);
      debugLogWidgetClass(_model);
    }
  }

  @override
  void didPush() {
    if (mounted) {
      setState(() => _model.isRouteVisible = true);
      debugLogWidgetClass(_model);
    }
  }

  @override
  void didPop() {
    _model.isRouteVisible = false;
  }

  @override
  void didPushNext() {
    _model.isRouteVisible = false;
  }

  @override
  Widget build(BuildContext context) {

    return Padding(
      padding: const EdgeInsetsDirectional.fromSTEB(16.0, 16.0, 16.0, 16.0),
      child: Container(
        width: double.infinity,
        decoration: BoxDecoration(
          color: const Color(0xFFFFF3CD),
          borderRadius: BorderRadius.circular(12.0),
          border: Border.all(
            color: const Color(0xFFFFEEBA),
            width: 1.0,
          ),
        ),
        child: Padding(
          padding: const EdgeInsetsDirectional.fromSTEB(12.0, 12.0, 12.0, 12.0),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              Row(
                mainAxisSize: MainAxisSize.max,
                mainAxisAlignment: MainAxisAlignment.start,
                children: [
                  const Icon(
                    Icons.warning_rounded,
                    color: Color(0xFF856404),
                    size: 24.0,
                  ),
                  Expanded(
                    child: Text(
                      FFLocalizations.of(context).getText(
                        '1f518kcb' /* Medical Disclaimer */,
                      ),
                      style: FlutterFlowTheme.of(context).titleMedium.override(
                            font: GoogleFonts.manrope(),
                            color: const Color(0xFF856404),
                            letterSpacing: 0.0,
                          ),
                    ),
                  ),
                ].divide(const SizedBox(width: 12.0)),
              ),
              Text(
                FFLocalizations.of(context).getText(
                  'fskqc96f' /* The content generated by AI is... */,
                ),
                style: FlutterFlowTheme.of(context).bodyMedium.override(
                      font: GoogleFonts.manrope(),
                      color: const Color(0xFF856404),
                      letterSpacing: 0.0,
                    ),
              ),
            ].divide(const SizedBox(height: 12.0)),
          ),
        ),
      ),
    );
  }
}
