export 'package:flutter/foundation.dart' show debugPrint;
// flutter_flow_util.dart — compatibility shim.
//
// The original flutter_flow/ directory was removed during the ST-1
// modernisation step. This file provides compatibility for all remaining
// code that still imports from here, mapping to new pure-Flutter equivalents.
//
// New code should import from '/core/core.dart' directly.

// ignore_for_file: unused_element, unused_import, duplicate_ignore

// ---------------------------------------------------------------------------
// Exports (must come before any declarations)
// ---------------------------------------------------------------------------
export 'dart:typed_data' show Uint8List;
export '/core/core.dart';
export 'package:flutter/material.dart';
export 'package:cloud_firestore/cloud_firestore.dart' hide Order;
export 'package:go_router/go_router.dart';
export '/core/router/app_router.dart'
    show
        GoRouterExtensions,
        NavigationExtensions,
        GoRouterLocationExtension,
        AppStateNotifier,
        RootPageContext,
        routeObserver,
        appNavigatorKey;

// ---------------------------------------------------------------------------
// Imports
// ---------------------------------------------------------------------------
import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:permission_handler/permission_handler.dart';
import '/app_state.dart';
import '/core/base_model.dart';
import '/core/debug/debug_types.dart';
import '/core/types/uploaded_file.dart';
import '/theme/app_theme.dart';
import '/flutter_flow/flutter_flow_animations.dart' show AnimationInfo;
import '/flutter_flow/upload_data.dart' show selectMedia, SelectedMedia, selectMediaWithSourceBottomSheet;


// ---------------------------------------------------------------------------
// createModel — FF helper to instantiate and initialize a model
// ---------------------------------------------------------------------------
T createModel<T extends BaseModel>(BuildContext context, T Function() creator) {
  final model = creator();
  model.init(context);
  return model;
}

// ---------------------------------------------------------------------------
// safeSetState — FF helper that calls setState only if mounted
// ---------------------------------------------------------------------------
extension SafeSetStateExtension on State {
  void safeSetState(VoidCallback fn) {
    if (mounted) {
      // ignore: invalid_use_of_protected_member
      setState(fn);
    }
  }
}

// ---------------------------------------------------------------------------
// FFLocalizations — full multilingual provider with legacy & ARB key support
// ---------------------------------------------------------------------------
class FFLocalizations {
  FFLocalizations._(this._locale);
  final Locale _locale;

  static FFLocalizations of(BuildContext context) =>
      FFLocalizations._(Localizations.localeOf(context));

  static Future<void> initialize() async {}

  static Future<Locale?> getStoredLocale() async {
    try {
      final prefs = await SharedPreferences.getInstance();
      final code = prefs.getString('aarogyam_language_code');
      return code != null ? Locale(code) : null;
    } catch (_) {
      return null;
    }
  }

  static Future<void> storeLocale(String language) async {
    try {
      final prefs = await SharedPreferences.getInstance();
      await prefs.setString('aarogyam_language_code', language);
    } catch (_) {}
  }

  Locale get locale => _locale;
  String get languageCode => _locale.languageCode;

  String getText(String key) {
    final lang = _locale.languageCode;
    final entry = _kTranslations[key];
    if (entry != null) {
      return entry[lang] ?? entry['en'] ?? key;
    }
    return key;
  }

  String getVariableText({String? enText = '', String? hiText, String? mrText}) {
    final code = _locale.languageCode;
    if (code == 'hi' && hiText != null && hiText.isNotEmpty) return hiText;
    if (code == 'mr' && mrText != null && mrText.isNotEmpty) return mrText;
    return enText ?? '';
  }
}

const Map<String, Map<String, String>> _kTranslations = {
  'aiDisclaimerBody': {'en': 'The content generated by AI is for informational purposes only and should not be considered as medical advice. Always consult with qualified healthcare professionals for proper medical diagnosis, treatment, and advice regarding your specific situation.', 'hi': 'AI द्वारा तैयार की गई सामग्री केवल सूचनात्मक उद्देश्यों के लिए है और इसे चिकित्सा सलाह के रूप में नहीं माना जाना चाहिए। अपनी विशिष्ट स्थिति के बारे में उचित चिकित्सा निदान, उपचार और सलाह के लिए हमेशा योग्य स्वास्थ्य सेवा पेशेवरों से परामर्श करें।', 'mr': 'AI द्वारे व्युत्पन्न केलेली सामग्री केवळ माहितीच्या उद्देशाने आहे आणि ती वैद्यकीय सल्ला म्हणून मानली जाऊ नये. तुमच्या विशिष्ट परिस्थितीशी संबंधित योग्य वैद्यकीय निदान, उपचार आणि सल्ल्यासाठी नेहमीच योग्य आरोग्यसेवा व्यावसायिकांशी सल्लामसलत करा.'},
  'aiDisclaimerTitle': {'en': 'Medical Disclaimer', 'hi': 'चिकित्सा अस्वीकरण', 'mr': 'वैद्यकीय अस्वीकरण'},
  'allergiesAnesthesia': {'en': 'Anesthesia (e.g., lidocaine)', 'hi': 'एनेस्थीसिया (उदा. लिडोकेन)', 'mr': 'ऍनेस्थेसिया (उदा. लिडोकेन)'},
  'allergiesAnimalDander': {'en': 'Animal dander (cats, dogs, etc.)', 'hi': 'पालतू पशुओं की रूसी (बिल्ली, कुत्ता)', 'mr': 'प्राण्यांचे केस व कोंडा (मांजर, कुत्रा)'},
  'allergiesAspirin': {'en': 'Aspirin', 'hi': 'एस्पिरिन (Aspirin)', 'mr': 'ॲस्पिरिन (Aspirin)'},
  'allergiesBeeSting': {'en': 'Bee stings', 'hi': 'मधुमक्खी का डंक', 'mr': 'मधमाशीचा डंक'},
  'allergiesChemicalTitle': {'en': 'Chemical and Skin Allergies', 'hi': 'रासायनिक और त्वचा एलर्जी', 'mr': 'रासायनिक आणि त्वचा ॲलर्जी (Chemical & Skin)'},
  'allergiesCleaningProducts': {'en': 'Cleaning products', 'hi': 'सफाई उत्पाद (Cleaning Products)', 'mr': 'सफाई उत्पादने (Cleaning Products)'},
  'allergiesCockroach': {'en': 'Cockroach droppings', 'hi': 'तिलचट्टे के अवशेष', 'mr': 'झुरळांची घाण'},
  'allergiesCold': {'en': 'Cold temperatures (cold urticaria)', 'hi': 'ठंडा तापमान (शीत पित्ती)', 'mr': 'थंड तापमान (थंड अर्टिकेरिया)'},
  'allergiesDustMites': {'en': 'Dust mites', 'hi': 'धूल के कीड़े (डस्ट माइट्स)', 'mr': 'धुळीचे कण (डस्ट माइट्स)'},
  'allergiesEggs': {'en': 'Eggs', 'hi': 'अंडे (Eggs)', 'mr': 'अंडी (Eggs)'},
  'allergiesEnvironmentalTitle': {'en': 'Environmental Allergies', 'hi': 'पर्यावरण संबंधी एलर्जी', 'mr': 'पर्यावरणीय ॲलर्जी (Environmental)'},
  'allergiesFireAnt': {'en': 'Fire ant bites', 'hi': 'लाल चींटी का डंक', 'mr': 'लाल मुंग्यांचे चावणे'},
  'allergiesFish': {'en': 'Fish (e.g., salmon, tuna)', 'hi': 'मछली (उदा. सैल्मन, टूना)', 'mr': 'मासे (उदा. सॅल्मन, ट्यूना)'},
  'allergiesFoodTitle': {'en': 'Food Allergies', 'hi': 'खाद्य एलर्जी (Food Allergies)', 'mr': 'अन्न ॲलर्जी (Food Allergies)'},
  'allergiesHairDye': {'en': 'Hair dyes or cosmetics', 'hi': 'हेयर डाई या सौंदर्य प्रसाधन', 'mr': 'हेअर डाय किंवा सौंदर्यप्रसाधने'},
  'allergiesIbuprofen': {'en': 'Ibuprofen', 'hi': 'आइबुप्रोफ़ेन (Ibuprofen)', 'mr': 'इबुप्रोफेन (Ibuprofen)'},
  'allergiesInsectTitle': {'en': 'Insect Allergies', 'hi': 'कीट एलर्जी (Insect)', 'mr': 'कीटकांची ॲलर्जी (Insect)'},
  'allergiesLatex': {'en': 'Latex', 'hi': 'लेटेक्स (Latex)', 'mr': 'लेटेक्स (Latex)'},
  'allergiesMedicationTitle': {'en': 'Medication Allergies', 'hi': 'दवाओं की एलर्जी (Medication)', 'mr': 'औषधांची ॲलर्जी (Medication)'},
  'allergiesMilk': {'en': 'Milk (lactose intolerance or dairy allergy)', 'hi': 'दूध (लैक्टोज असहिष्णुता या डेयरी एलर्जी)', 'mr': 'दूध (लॅक्टोज असहिष्णुता किंवा दुग्धजन्य ॲलर्जी)'},
  'allergiesMold': {'en': 'Mold spores', 'hi': 'फफूंद बीजाणु (मोल्ड स्पोर्स)', 'mr': 'बुरशीचे बीजाणू (मोल्ड स्पोर्स)'},
  'allergiesMosquito': {'en': 'Mosquito bites', 'hi': 'मच्छर का काटना', 'mr': 'डास चावणे'},
  'allergiesNickel': {'en': 'Nickel (in jewelry or clothing)', 'hi': 'निकेल (आभूषणों या कपड़ों में)', 'mr': 'निकेल (दागिने किंवा कपड्यांमध्ये)'},
  'allergiesOther': {'en': 'Other...', 'hi': 'अन्य...', 'mr': 'इतर...'},
  'allergiesPeanuts': {'en': 'Peanuts', 'hi': 'मूंगफली (Peanuts)', 'mr': 'शेंगदाणे (Peanuts)'},
  'allergiesPenicillin': {'en': 'Penicillin or other antibiotics', 'hi': 'पेनिसिलिन या अन्य एंटीबायोटिक्स', 'mr': 'पेनिसिलीन किंवा इतर प्रतिजैविक'},
  'allergiesPerfume': {'en': 'Perfumes or fragrances', 'hi': 'इत्र या सुगंध (Fragrance)', 'mr': 'परफ्यूम किंवा सुगंध (Fragrance)'},
  'allergiesPollen': {'en': 'Pollen (grass, trees, or flowers)', 'hi': 'पराग (घास, पेड़ या फूल)', 'mr': 'परागकण (गवत, झाडे किंवा फुले)'},
  'allergiesRareTitle': {'en': 'Rare or Less Common Allergies', 'hi': 'दुर्लभ या कम आम एलर्जी (Rare)', 'mr': 'दुर्मिळ किंवा कमी सामान्य ॲलर्जी (Rare)'},
  'allergiesSave': {'en': 'Save', 'hi': 'सुरक्षित करें', 'mr': 'जतन करा'},
  'allergiesSelectTitle': {'en': 'Select Your Allergies', 'hi': 'अपनी एलर्जी चुनें', 'mr': 'तुमची ऍलर्जी निवडा'},
  'allergiesShellfish': {'en': 'Shellfish (e.g., shrimp, crab, lobster)', 'hi': 'शेलफिश (उदा. झींगा, केकड़ा, लॉबस्टर)', 'mr': 'शेलफिश (उदा. कोळंबी, खेकडा, लॉबस्टर)'},
  'allergiesSoap': {'en': 'Soaps or detergents', 'hi': 'साबुन या डिटर्जेंट (Soaps)', 'mr': 'साबण किंवा डिटर्जंट (Soaps)'},
  'allergiesSoy': {'en': 'Soy', 'hi': 'सोया (Soy)', 'mr': 'सोया (Soy)'},
  'allergiesSpecifyHere': {'en': 'Specify  your allergy here...', 'hi': 'अपनी एलर्जी यहां बताएं...', 'mr': 'तुमची ॲलर्जी येथे नमूद करा...'},
  'allergiesSubtitle': {'en': 'Let us know what triggers your allergies to help you stay safe.', 'hi': 'हमें बताएं कि आपकी एलर्जी किस कारण से होती है ताकि आप सुरक्षित रह सकें।', 'mr': 'तुम्हाला सुरक्षित राहण्यात मदत करण्यासाठी तुमच्या ॲलर्जी कशामुळे उत्पन्न होते ते आम्हाला कळवा.'},
  'allergiesSulfa': {'en': 'Sulfa drugs', 'hi': 'सल्फ़ा दवाएं', 'mr': 'सल्फा औषधे'},
  'allergiesSunlight': {'en': 'Sunlight (photosensitivity)', 'hi': 'सूर्य का प्रकाश (प्रकाश संवेदनशीलता)', 'mr': 'सूर्यप्रकाश (फोटोसंवेदनशीलता)'},
  'allergiesTitle': {'en': 'Allergies', 'hi': 'एलर्जी', 'mr': 'ऍलर्जी'},
  'allergiesTreeNuts': {'en': 'Tree nuts (e.g., almonds, walnuts)', 'hi': 'ट्री नट्स (उदा. बादाम, अखरोट)', 'mr': 'ट्री नट्स (उदा. बदाम, अक्रोड)'},
  'allergiesWaspSting': {'en': 'Wasp stings', 'hi': 'ततैया का डंक', 'mr': 'गांधील माशीचा डंक'},
  'allergiesWater': {'en': 'Water (aquagenic urticaria)', 'hi': 'जल (एक्वाजेनिक अर्टिकेरिया)', 'mr': 'पाणी (एक्वाजेनिक अर्टिकेरिया)'},
  'allergiesWheat': {'en': 'Wheat (gluten intolerance or allergy)', 'hi': 'गेहूँ (ग्लूटेन असहिष्णुता या एलर्जी)', 'mr': 'गहू (ग्लूटेन असहिष्णुता किंवा ॲलर्जी)'},
  'authHomeDescription': {'en': 'You can delete this and create your home page here.', 'hi': 'आप इसे हटा सकते हैं और यहां अपना होम पेज बना सकते हैं।', 'mr': 'तुम्ही हे हटवू शकता आणि तुमचे मुख्यपृष्ठ येथे तयार करू शकता.'},
  'authHomeTitle': {'en': 'Home', 'hi': 'घर', 'mr': 'घर'},
  'authUserInfoSubtitle': {'en': 'Help us personalize your experience.', 'hi': 'अपने अनुभव को निजीकृत करने में हमारी सहायता करें।', 'mr': 'आम्हाला तुमचा अनुभव वैयक्तिकृत करण्यात मदत करा.'},
  'chatBotHint': {'en': 'Ask Sanjeevani...', 'hi': 'संजीवनी से पूछें...', 'mr': 'संजीवनीला विचारा...'},
  'chatBotName': {'en': 'Sanjeevani', 'hi': 'संजीवनी', 'mr': 'संजीवनी'},
  'chatBotTitle': {'en': 'संजीवनी', 'hi': 'संजीवनी', 'mr': 'संजीवनी'},
  'createAccountButton': {'en': 'Create Account', 'hi': 'खाता बनाएं', 'mr': 'खाते तयार करा'},
  'createAccountDisplayName': {'en': 'Display Name', 'hi': 'प्रदर्शित होने वाला नाम', 'mr': 'डिस्प्ले नाव'},
  'createAccountEmail': {'en': 'Email Address', 'hi': 'मेल पता', 'mr': 'ईमेल पत्ता'},
  'createAccountPassword': {'en': 'Password', 'hi': 'पासवर्ड', 'mr': 'पासवर्ड'},
  'createAccountSubtitle': {'en': 'Your health, your responsibilty.', 'hi': 'आपका स्वास्थ्य, आपकी जिम्मेदारी.', 'mr': 'तुमचे आरोग्य, तुमची जबाबदारी.'},
  'createAccountTitle': {'en': 'Welcome to Aarogyam!', 'hi': 'आरोग्यम में आपका स्वागत है!', 'mr': 'आरोग्यम मध्ये आपले स्वागत आहे!'},
  'customQueryDone': {'en': 'Done', 'hi': 'हो गया', 'mr': 'झाले'},
  'customQueryGenericAlternatives': {'en': 'Suggest Generic Alternatives', 'hi': 'सामान्य विकल्प सुझाएँ', 'mr': 'जेनेरिक पर्याय सुचवा'},
  'customQueryLifestyle': {'en': 'Suggest Lifestyle Activities', 'hi': 'जीवनशैली गतिविधियाँ सुझाएँ', 'mr': 'जीवनशैली उपक्रम सुचवा'},
  'customQueryOrSelect': {'en': 'or select from below', 'hi': 'या नीचे से चुनें', 'mr': 'किंवा खालीलपैकी निवडा'},
  'customQueryPainkillers': {'en': 'Check for Painkillers', 'hi': 'दर्द निवारक दवाओं की जांच करें', 'mr': 'पेनकिलर तपासा'},
  'customQueryQueryHint': {'en': 'Write your query here', 'hi': 'अपना प्रश्न यहां लिखें', 'mr': 'तुमची क्वेरी इथे लिहा'},
  'customQueryQueryLabel': {'en': 'Query', 'hi': 'सवाल', 'mr': 'क्वेरी'},
  'customQuerySubtitle': {'en': 'Define the specific information you want to extract or analyze below.', 'hi': 'नीचे वह विशिष्ट जानकारी परिभाषित करें जिसे आप निकालना या विश्लेषण करना चाहते हैं।', 'mr': 'तुम्हाला खाली काढायची किंवा विश्लेषण करायची असलेली विशिष्ट माहिती परिभाषित करा.'},
  'customQueryTitle': {'en': 'Customize Your Response', 'hi': 'अपना जवाब अनुकूलित करें', 'mr': 'तुमचा प्रतिसाद सानुकूलित करा'},
  'customQueryTitleHint': {'en': 'Write Title for your query', 'hi': 'अपने प्रश्न के लिए शीर्षक लिखें', 'mr': 'तुमच्या प्रश्नासाठी शीर्षक लिहा'},
  'customQueryTitleLabel': {'en': 'Title', 'hi': 'शीर्षक', 'mr': 'शीर्षक'},
  'customQueryUrgentActions': {'en': 'Check Urguent Actions', 'hi': 'ज़रूरी कार्रवाई की जाँच करें', 'mr': 'त्वरित कृती तपासा'},
  'dbpageTitle': {'en': 'Page Title', 'hi': 'पृष्ठ शीर्षक', 'mr': 'पृष्ठ शीर्षक'},
  'firstAidTitle': {'en': 'First Aid', 'hi': 'प्राथमिक चिकित्सा', 'mr': 'प्रथमोपचार'},
  'forgotPasswordButton': {'en': 'Send Link', 'hi': 'लिंक भेजें', 'mr': 'लिंक पाठवा'},
  'forgotPasswordEmail': {'en': 'Email Address', 'hi': 'मेल पता', 'mr': 'ईमेल पत्ता'},
  'forgotPasswordSubtitle': {'en': 'We will send you a reset link.', 'hi': 'हम आपको एक रीसेट लिंक भेजेंगे.', 'mr': 'आम्ही तुम्हाला रीसेट लिंक पाठवू.'},
  'forgotPasswordTitle': {'en': 'Forgot Password', 'hi': 'पासवर्ड भूल गए', 'mr': 'पासवर्ड विसरलात'},
  'homeFirstAid': {'en': 'First Aid', 'hi': 'प्राथमिक चिकित्सा', 'mr': 'प्रथमोपचार'},
  'homeReportScanner': {'en': 'Report Scanner', 'hi': 'रिपोर्ट स्कैनर', 'mr': 'अहवाल स्कॅनर'},
  'homeSanjeevani': {'en': 'Sanjeevani', 'hi': 'संजीवनी', 'mr': 'संजीवनी'},
  'homeSwipeCards': {'en': 'Swipe the cards', 'hi': 'कार्ड स्वाइप करें', 'mr': 'कार्ड स्वाइप करा'},
  'homeTitle': {'en': 'आरोग्यम् धनसंपदा', 'hi': 'आरोग्यम् धनसंपदा', 'mr': 'आरोग्यम् धनसंपदा'},
  'loginButton': {'en': 'Login', 'hi': 'लॉग इन करें', 'mr': 'लॉगिन करा'},
  'loginEmail': {'en': 'Email Address', 'hi': 'मेल पता', 'mr': 'ईमेल पत्ता'},
  'loginForgotPassword': {'en': 'Forgot Password?', 'hi': 'पासवर्ड भूल गए?', 'mr': 'पासवर्ड विसरलात?'},
  'loginPassword': {'en': 'Password', 'hi': 'पासवर्ड', 'mr': 'पासवर्ड'},
  'loginSubtitle': {'en': 'Access your health tools by logging in below.', 'hi': 'नीचे लॉग इन करके अपने स्वास्थ्य उपकरणों तक पहुंचें।', 'mr': 'खाली लॉग इन करून तुमच्या आरोग्य साधनांमध्ये प्रवेश करा.'},
  'loginTitle': {'en': 'Get to my account', 'hi': 'मेरे खाते पर जाएं', 'mr': 'माझ्या खात्यावर जा'},
  'miscNotify': {'en': 'notify', 'hi': 'सूचित करें', 'mr': 'सूचित करा'},
  'miscScheduleNotifications': {'en': 'Schedule Notifications', 'hi': 'अधिसूचनाएँ शेड्यूल करें', 'mr': 'सूचना शेड्यूल करा'},
  'miscVoiceChat': {'en': 'For voice chat', 'hi': 'वॉयस चैट के लिए', 'mr': 'व्हॉइस चॅटसाठी'},
  'navHome': {'en': 'Home', 'hi': 'घर', 'mr': 'घर'},
  'profileButton': {'en': 'Button', 'hi': 'बटन', 'mr': 'बटण'},
  'profileCopyDisplayName': {'en': '[Display name]', 'hi': '[प्रदर्शित होने वाला नाम]', 'mr': '[नाव प्रदर्शित करा]'},
  'profileCopyEmail': {'en': '[Email id]', 'hi': '[ईमेल आईडी]', 'mr': '[ईमेल आयडी]'},
  'profileInsights': {'en': 'Insights', 'hi': 'इनसाइट्स', 'mr': 'अंतर्दृष्टी'},
  'profilePrescription': {'en': 'Prescription', 'hi': 'नुस्खा', 'mr': 'प्रिस्क्रिप्शन'},
  'profileTitle': {'en': 'Profile', 'hi': 'प्रोफ़ाइल', 'mr': 'प्रोफाइल'},
  'reminderPageTitle': {'en': 'Home', 'hi': 'घर', 'mr': 'घर'},
  'remindersTitle': {'en': 'Reminders', 'hi': 'अनुस्मारक', 'mr': 'स्मरणपत्रे'},
  'reportScannerCustomQuery': {'en': 'Set your own query', 'hi': 'अपनी स्वयं की क्वेरी सेट करें', 'mr': 'तुमची स्वतःची क्वेरी सेट करा'},
  'reportScannerPrescriptionAnalysis': {'en': 'Prescription Analysis', 'hi': 'प्रिस्क्रिप्शन विश्लेषण', 'mr': 'प्रिस्क्रिप्शन विश्लेषण'},
  'reportScannerQuestion': {'en': 'What are you looking for?', 'hi': 'तुम क्या ढूंढ रहे हो?', 'mr': 'आपण काय शोधत आहात?'},
  'reportScannerReportInsights': {'en': 'Report Insights', 'hi': 'रिपोर्ट अंतर्दृष्टि', 'mr': 'अहवाल अंतर्दृष्टी'},
  'reportScannerTitle': {'en': 'Upload Image Here', 'hi': 'छवि यहां अपलोड करें', 'mr': 'येथे प्रतिमा अपलोड करा'},
  'responsePageAppendTxt': {'en': 'appendTXT', 'hi': 'एपेंडTXT', 'mr': 'TXT संलग्न करा'},
  'responsePageExtractMedications': {'en': 'extractmedications', 'hi': 'अर्कदवाएं', 'mr': 'अर्क औषधे'},
  'responsePageInsights': {'en': 'Insights', 'hi': 'इनसाइट्स', 'mr': 'अंतर्दृष्टी'},
  'responsePageNotification': {'en': 'awsmnotification', 'hi': 'awsmनोटिफिकेशन', 'mr': 'awsmnotification'},
  'responsePageRemainder': {'en': 'Remainder', 'hi': 'शेष', 'mr': 'बाकी'},
  'responsePageSaveTxt': {'en': 'saveTXT', 'hi': 'सेवTXT', 'mr': 'सेव्ह टीएक्सटी'},
  'responsePageSetNotification': {'en': 'setawsmnotifi', 'hi': 'setawsmnotifi (सेटएडब्ल्यूएसएमएनओटीआईएफआइ)', 'mr': 'setawsmnotifi'},
  'responsePageUpdated': {'en': 'updatedbb', 'hi': 'अपडेटेडबीबी', 'mr': 'अद्यतनित bb'},
  'setReminderDescriptionHint': {'en': 'eg. Dosage', 'hi': 'उदाहरण: खुराक', 'mr': 'उदा. डोस'},
  'setReminderDescriptionLabel': {'en': 'Discription', 'hi': 'विवरण', 'mr': 'वर्णन'},
  'setReminderTime': {'en': 'Time', 'hi': 'समय', 'mr': 'वेळ'},
  'setReminderTitle': {'en': 'Set Reminder', 'hi': 'अनुस्मारक सेट करें', 'mr': 'स्मरणपत्र सेट करा'},
  'setReminderTitleHint': {'en': 'eg. Medicine or task', 'hi': 'जैसे: दवा या कार्य', 'mr': 'उदा. औषध किंवा कार्य'},
  'setReminderTitleLabel': {'en': 'Title', 'hi': 'शीर्षक', 'mr': 'शीर्षक'},
  'userInfoAge': {'en': 'Age', 'hi': 'आयु', 'mr': 'वय'},
  'userInfoAllergies': {'en': 'Allergies(If any)', 'hi': 'एलर्जी (यदि कोई हो)', 'mr': 'ऍलर्जी (असल्यास)'},
  'userInfoFemale': {'en': 'Female', 'hi': 'महिला', 'mr': 'स्त्री'},
  'userInfoGender': {'en': 'Gender', 'hi': 'लिंग', 'mr': 'लिंग'},
  'userInfoGenderSearch': {'en': 'Search...', 'hi': 'खोज...', 'mr': 'शोधा...'},
  'userInfoHeight': {'en': 'Height(cm)', 'hi': 'ऊंचाई(सेमी)', 'mr': 'उंची (सेमी)'},
  'userInfoMale': {'en': 'Male', 'hi': 'पुरुष', 'mr': 'पुरुष'},
  'userInfoOther': {'en': 'Other', 'hi': 'अन्य', 'mr': 'इतर'},
  'userInfoWeight': {'en': 'Weight(kg)', 'hi': 'वजन (किलोग्राम)', 'mr': 'वजन (किलो)'},
  'welcomeAppName': {'en': 'aarogyam', 'hi': 'आरोग्यम', 'mr': 'आरोग्यम'},
  'welcomeCreateAccount': {'en': 'Create an Account', 'hi': 'खाता बनाएं', 'mr': 'खाते तयार करा'},
  'welcomeLogin': {'en': 'Login', 'hi': 'लॉग इन करें', 'mr': 'लॉगिन करा'},
  'welcomeSubtitle': {'en': 'Welcomes You!', 'hi': 'आप का स्वागत है!', 'mr': 'तुमचे स्वागत आहे!'},
  'welcomeTagline': {'en': 'Health Made Easy \nBecause You Deserve to Know!', 'hi': 'स्वास्थ्य को आसान बनाएं\nक्योंकि आपको जानने का हक है!', 'mr': 'आरोग्य सोपे केले \nकारण तुम्ही जाणून घेण्यास पात्र आहात!'},
  '14h9zxpt': {'en': 'Soaps or detergents', 'hi': 'साबुन या डिटर्जेंट (Soaps)', 'mr': 'साबण किंवा डिटर्जंट (Soaps)'},
  '1f518kcb': {'en': 'Medical Disclaimer', 'hi': 'चिकित्सा अस्वीकरण', 'mr': 'वैद्यकीय अस्वीकरण'},
  '2vo7do12': {'en': 'Fire ant bites', 'hi': 'लाल चींटी का डंक', 'mr': 'लाल मुंग्यांचे चावणे'},
  '36jtdw0y': {'en': 'Soy', 'hi': 'सोया (Soy)', 'mr': 'सोया (Soy)'},
  '37n9p1o8': {'en': 'Tree nuts (e.g., almonds, walnuts)', 'hi': 'ट्री नट्स (उदा. बादाम, अखरोट)', 'mr': 'ट्री नट्स (उदा. बदाम, अक्रोड)'},
  '64z8bhud': {'en': 'Medication Allergies', 'hi': 'दवाओं की एलर्जी (Medication)', 'mr': 'औषधांची ॲलर्जी (Medication)'},
  '6keaylqw': {'en': 'Mold spores', 'hi': 'फफूंद बीजाणु (मोल्ड स्पोर्स)', 'mr': 'बुरशीचे बीजाणू (मोल्ड स्पोर्स)'},
  '7b9jl64z': {'en': 'Other...', 'hi': 'अन्य...', 'mr': 'इतर...'},
  '7izmft2n': {'en': 'Milk (lactose intolerance or dairy allergy)', 'hi': 'दूध (लैक्टोज असहिष्णुता या डेयरी एलर्जी)', 'mr': 'दूध (लॅक्टोज असहिष्णुता किंवा दुग्धजन्य ॲलर्जी)'},
  '8h8cqv82': {'en': 'Perfumes or fragrances', 'hi': 'इत्र या सुगंध (Fragrance)', 'mr': 'परफ्यूम किंवा सुगंध (Fragrance)'},
  '8q12e1nz': {'en': 'Ibuprofen', 'hi': 'आइबुप्रोफ़ेन (Ibuprofen)', 'mr': 'इबुप्रोफेन (Ibuprofen)'},
  '9bzu7qmj': {'en': 'Cockroach droppings', 'hi': 'तिलचट्टे के अवशेष', 'mr': 'झुरळांची घाण'},
  '9e10du1m': {'en': 'Title', 'hi': 'शीर्षक', 'mr': 'शीर्षक'},
  '9vzp42f0': {'en': 'Sunlight (photosensitivity)', 'hi': 'सूर्य का प्रकाश (प्रकाश संवेदनशीलता)', 'mr': 'सूर्यप्रकाश (फोटोसंवेदनशीलता)'},
  'a0sjqk93': {'en': 'Aspirin', 'hi': 'एस्पिरिन (Aspirin)', 'mr': 'ॲस्पिरिन (Aspirin)'},
  'awbn2z6g': {'en': 'Hair dyes or cosmetics', 'hi': 'हेयर डाई या सौंदर्य प्रसाधन', 'mr': 'हेअर डाय किंवा सौंदर्यप्रसाधने'},
  'bh2supoy': {'en': 'Cleaning products', 'hi': 'सफाई उत्पाद (Cleaning Products)', 'mr': 'सफाई उत्पादने (Cleaning Products)'},
  'bjxvernh': {'en': 'Animal dander (cats, dogs, etc.)', 'hi': 'पालतू पशुओं की रूसी (बिल्ली, कुत्ता)', 'mr': 'प्राण्यांचे केस व कोंडा (मांजर, कुत्रा)'},
  'cm02jy6i': {'en': 'Nickel (in jewelry or clothing)', 'hi': 'निकेल (आभूषणों या कपड़ों में)', 'mr': 'निकेल (दागिने किंवा कपड्यांमध्ये)'},
  'dptbbc68': {'en': 'Discription', 'hi': 'विवरण', 'mr': 'वर्णन'},
  'eif9fchm': {'en': 'Anesthesia (e.g., lidocaine)', 'hi': 'एनेस्थीसिया (उदा. लिडोकेन)', 'mr': 'ऍनेस्थेसिया (उदा. लिडोकेन)'},
  'epom6kvc': {'en': 'Specify  your allergy here...', 'hi': 'अपनी एलर्जी यहां बताएं...', 'mr': 'तुमची ॲलर्जी येथे नमूद करा...'},
  'fskqc96f': {'en': 'The content generated by AI is for informational purposes only and should not be considered as medical advice. Always consult with qualified healthcare professionals for proper medical diagnosis, treatment, and advice regarding your specific situation.', 'hi': 'AI द्वारा तैयार की गई सामग्री केवल सूचनात्मक उद्देश्यों के लिए है और इसे चिकित्सा सलाह के रूप में नहीं माना जाना चाहिए। अपनी विशिष्ट स्थिति के बारे में उचित चिकित्सा निदान, उपचार और सलाह के लिए हमेशा योग्य स्वास्थ्य सेवा पेशेवरों से परामर्श करें।', 'mr': 'AI द्वारे व्युत्पन्न केलेली सामग्री केवळ माहितीच्या उद्देशाने आहे आणि ती वैद्यकीय सल्ला म्हणून मानली जाऊ नये. तुमच्या विशिष्ट परिस्थितीशी संबंधित योग्य वैद्यकीय निदान, उपचार आणि सल्ल्यासाठी नेहमीच योग्य आरोग्यसेवा व्यावसायिकांशी सल्लामसलत करा.'},
  'fx69e3ab': {'en': 'eg. Medicine or task', 'hi': 'जैसे: दवा या कार्य', 'mr': 'उदा. औषध किंवा कार्य'},
  'gu9iyur9': {'en': 'Dust mites', 'hi': 'धूल के कीड़े (डस्ट माइट्स)', 'mr': 'धुळीचे कण (डस्ट माइट्स)'},
  'hfdspp28': {'en': 'Insect Allergies', 'hi': 'कीट एलर्जी (Insect)', 'mr': 'कीटकांची ॲलर्जी (Insect)'},
  'hjr8gu65': {'en': 'Shellfish (e.g., shrimp, crab, lobster)', 'hi': 'शेलफिश (उदा. झींगा, केकड़ा, लॉबस्टर)', 'mr': 'शेलफिश (उदा. कोळंबी, खेकडा, लॉबस्टर)'},
  'hlok3i89': {'en': 'Set Reminder', 'hi': 'अनुस्मारक सेट करें', 'mr': 'स्मरणपत्र सेट करा'},
  'iigpgbl4': {'en': 'Cold temperatures (cold urticaria)', 'hi': 'ठंडा तापमान (शीत पित्ती)', 'mr': 'थंड तापमान (थंड अर्टिकेरिया)'},
  'ikcmg4a2': {'en': '[Display name]', 'hi': '[प्रदर्शित होने वाला नाम]', 'mr': '[नाव प्रदर्शित करा]'},
  'j1s401z6': {'en': '[Email id]', 'hi': '[ईमेल आईडी]', 'mr': '[ईमेल आयडी]'},
  'jj1guz3s': {'en': 'Sulfa drugs', 'hi': 'सल्फ़ा दवाएं', 'mr': 'सल्फा औषधे'},
  'jqoiqi58': {'en': 'Wheat (gluten intolerance or allergy)', 'hi': 'गेहूँ (ग्लूटेन असहिष्णुता या एलर्जी)', 'mr': 'गहू (ग्लूटेन असहिष्णुता किंवा ॲलर्जी)'},
  'luilux78': {'en': 'Rare or Less Common Allergies', 'hi': 'दुर्लभ या कम आम एलर्जी (Rare)', 'mr': 'दुर्मिळ किंवा कमी सामान्य ॲलर्जी (Rare)'},
  'mim19fdt': {'en': 'Save', 'hi': 'सुरक्षित करें', 'mr': 'जतन करा'},
  'nxg05p9w': {'en': 'Fish (e.g., salmon, tuna)', 'hi': 'मछली (उदा. सैल्मन, टूना)', 'mr': 'मासे (उदा. सॅल्मन, ट्यूना)'},
  'p629h6qb': {'en': 'Water (aquagenic urticaria)', 'hi': 'जल (एक्वाजेनिक अर्टिकेरिया)', 'mr': 'पाणी (एक्वाजेनिक अर्टिकेरिया)'},
  'qdc6xo57': {'en': 'Penicillin or other antibiotics', 'hi': 'पेनिसिलिन या अन्य एंटीबायोटिक्स', 'mr': 'पेनिसिलीन किंवा इतर प्रतिजैविक'},
  'qrb48q63': {'en': 'Mosquito bites', 'hi': 'मच्छर का काटना', 'mr': 'डास चावणे'},
  'qwldzxs0': {'en': 'Eggs', 'hi': 'अंडे (Eggs)', 'mr': 'अंडी (Eggs)'},
  'rut7wupc': {'en': 'Chemical and Skin Allergies', 'hi': 'रासायनिक और त्वचा एलर्जी', 'mr': 'रासायनिक आणि त्वचा ॲलर्जी (Chemical & Skin)'},
  's95pj3uk': {'en': 'eg. Dosage', 'hi': 'उदाहरण: खुराक', 'mr': 'उदा. डोस'},
  'uqs4gk20': {'en': 'Pollen (grass, trees, or flowers)', 'hi': 'पराग (घास, पेड़ या फूल)', 'mr': 'परागकण (गवत, झाडे किंवा फुले)'},
  'usb32aa0': {'en': 'Bee stings', 'hi': 'मधुमक्खी का डंक', 'mr': 'मधमाशीचा डंक'},
  'v4cvorwt': {'en': 'Allergies', 'hi': 'एलर्जी', 'mr': 'ऍलर्जी'},
  'v4it3cs8': {'en': 'Food Allergies', 'hi': 'खाद्य एलर्जी (Food Allergies)', 'mr': 'अन्न ॲलर्जी (Food Allergies)'},
  'vvabksjy': {'en': 'Latex', 'hi': 'लेटेक्स (Latex)', 'mr': 'लेटेक्स (Latex)'},
  'vwymmhv4': {'en': 'Time', 'hi': 'समय', 'mr': 'वेळ'},
  'xcfte37b': {'en': 'Environmental Allergies', 'hi': 'पर्यावरण संबंधी एलर्जी', 'mr': 'पर्यावरणीय ॲलर्जी (Environmental)'},
  'xitz7pac': {'en': 'Peanuts', 'hi': 'मूंगफली (Peanuts)', 'mr': 'शेंगदाणे (Peanuts)'},
  'ykntkkju': {'en': 'Wasp stings', 'hi': 'ततैया का डंक', 'mr': 'गांधील माशीचा डंक'},
};


Locale createLocale(String language) => Locale(language);

// ---------------------------------------------------------------------------
// DebugModalRoute — delegates to real ModalRoute.of for routeObserver.subscribe
// ---------------------------------------------------------------------------
class DebugModalRoute {
  static ModalRoute? of(BuildContext context) => ModalRoute.of(context);
}


// ---------------------------------------------------------------------------
// wrapWithModel — wraps a child widget, passing through as-is
// ---------------------------------------------------------------------------
Widget wrapWithModel<T extends BaseModel>({
  required T model,
  required VoidCallback updateCallback,
  required Widget child,
  bool updateOnChange = false,
}) {
  if (updateOnChange) {
    model.addListener(updateCallback);
  }
  return child;
}

// ---------------------------------------------------------------------------
// divide() — FF helper for ListView dividers
// ---------------------------------------------------------------------------
extension ListDivideExtension<T extends Widget> on Iterable<T> {
  List<Widget> divide(Widget t) {
    final result = <Widget>[];
    for (final widget in this) {
      if (result.isNotEmpty) result.add(t);
      result.add(widget);
    }
    return result;
  }
}

// ---------------------------------------------------------------------------
// TextStyle.override — FF extension for easy text style customization
// ---------------------------------------------------------------------------
extension TextStyleOverride on TextStyle {
  TextStyle override({
    TextStyle? font,
    String? fontFamily,
    Color? color,
    double? fontSize,
    FontWeight? fontWeight,
    double? letterSpacing,
    FontStyle? fontStyle,
    TextDecoration? decoration,
    double? lineHeight,
    List<Shadow>? shadows,
    bool useGoogleFonts = false,
  }) {
    final base = font ?? this;
    return base.copyWith(
      fontFamily: fontFamily ?? base.fontFamily,
      color: color,
      fontSize: fontSize,
      fontWeight: fontWeight,
      letterSpacing: letterSpacing,
      fontStyle: fontStyle,
      decoration: decoration,
      height: lineHeight,
      shadows: shadows,
    );
  }
}

// ---------------------------------------------------------------------------
// FFAppState shim — returns the AppState singleton
// ---------------------------------------------------------------------------
// ignore: non_constant_identifier_names
AppState FFAppState() => AppState();

// ---------------------------------------------------------------------------
// FFButtonOptions / FFButtonWidget
// ---------------------------------------------------------------------------
class FFButtonOptions {
  const FFButtonOptions({
    this.width,
    this.height,
    this.padding,
    this.iconPadding,
    this.color,
    this.textStyle,
    this.elevation,
    this.borderSide,
    this.borderRadius,
    this.disabledColor,
    this.disabledTextColor,
    this.splashColor,
    this.iconColor,
    this.iconSize,
    this.iconAlignment,
    this.hoverColor,
    this.hoverTextColor,
    this.hoverBorderSide,
  });
  final double? width;
  final double? height;
  final EdgeInsetsGeometry? padding;
  final EdgeInsetsGeometry? iconPadding;
  final Color? color;
  final TextStyle? textStyle;
  final double? elevation;
  final BorderSide? borderSide;
  final BorderRadius? borderRadius;
  final Color? disabledColor;
  final Color? disabledTextColor;
  final Color? splashColor;
  final Color? iconColor;
  final double? iconSize;
  final dynamic iconAlignment;
  final Color? hoverColor;
  final Color? hoverTextColor;
  final BorderSide? hoverBorderSide;
}

class FFButtonWidget extends StatelessWidget {
  const FFButtonWidget({
    super.key,
    required this.onPressed,
    required this.text,
    required this.options,
    this.icon,
    this.iconData,
    this.showLoadingIndicator = true,
  });
  final VoidCallback? onPressed;
  final String text;
  final FFButtonOptions options;
  final Widget? icon;
  final IconData? iconData;
  final bool showLoadingIndicator;

  @override
  Widget build(BuildContext context) {
    Widget label = Text(text, style: options.textStyle);
    if (icon != null || iconData != null) {
      label = Row(
        mainAxisSize: MainAxisSize.min,
        children: [
          icon ?? Icon(iconData, size: options.iconSize ?? 20, color: options.iconColor),
          const SizedBox(width: 8),
          Text(text, style: options.textStyle),
        ],
      );
    }
    return SizedBox(
      width: options.width,
      height: options.height ?? 44,
      child: ElevatedButton(
        onPressed: onPressed,
        style: ElevatedButton.styleFrom(
          backgroundColor: options.color,
          elevation: options.elevation,
          padding: options.padding,
          shape: options.borderRadius != null
              ? RoundedRectangleBorder(
                  borderRadius: options.borderRadius!,
                  side: options.borderSide ?? BorderSide.none,
                )
              : null,
          disabledBackgroundColor: options.disabledColor,
          disabledForegroundColor: options.disabledTextColor,
        ),
        child: label,
      ),
    );
  }
}

// ---------------------------------------------------------------------------
// valueOrDefault — returns value if non-null/non-empty, else defaultValue
// ---------------------------------------------------------------------------
T valueOrDefault<T>(T? value, T defaultValue) =>
    (value is String && (value as String).isEmpty) || value == null
        ? defaultValue
        : value;

// ---------------------------------------------------------------------------
// DateTime.secondsSinceEpoch
// ---------------------------------------------------------------------------
extension DateTimeExtension on DateTime {
  int get secondsSinceEpoch => millisecondsSinceEpoch ~/ 1000;
}

// ---------------------------------------------------------------------------
// Permission constants
// ---------------------------------------------------------------------------
const Permission notificationsPermission = Permission.notification;
const Permission microphonePermission = Permission.microphone;

// ---------------------------------------------------------------------------
// FlutterFlowDynamicModels — dynamic sub-model collection
// ---------------------------------------------------------------------------
class FlutterFlowDynamicModels<T extends BaseModel> {
  FlutterFlowDynamicModels(this._creator);
  final T Function() _creator;
  final Map<String, T> _models = {};

  T getModel(String uid, int index) =>
      _models.putIfAbsent(uid, _creator);

  T? get(String uid) => _models[uid];

  void dispose() {
    for (final m in _models.values) {
      m.dispose();
    }
    _models.clear();
  }
}

// ---------------------------------------------------------------------------
// validateFileFormat — stub
// ---------------------------------------------------------------------------
bool validateFileFormat(String filePath, BuildContext context) => true;

// ---------------------------------------------------------------------------
// animateOnActionTrigger — flutter_animate stub extension
// ---------------------------------------------------------------------------
extension AnimateOnActionTriggerExtension on Widget {
  Widget animateOnActionTrigger(
    AnimationInfo? info, {
    bool hasBeenTriggered = false,
  }) =>
      this;
}

// ---------------------------------------------------------------------------
// setDarkModeSetting — theme mode toggle
// ---------------------------------------------------------------------------
Future<void> setDarkModeSetting(BuildContext context, ThemeMode mode) async {
  AppTheme.saveThemeMode(mode);
}

// ---------------------------------------------------------------------------
// startAudioRecording / stopAudioRecording — stubs for legacy profile page
// ---------------------------------------------------------------------------
Future<void> startAudioRecording(
  BuildContext context, {
  dynamic audioRecorder,
  dynamic onRecordingComplete,
  String? audioName,
}) async {}

Future<String?> stopAudioRecording({
  dynamic audioRecorder,
  String? audioName,
  void Function(String?, Uint8List?)? onRecordingComplete,
}) async {
  onRecordingComplete?.call(null, null);
  return null;
}

// ---------------------------------------------------------------------------
// addToEnd / addToStart — chainable list append/prepend
// ---------------------------------------------------------------------------
extension ListAddExtension<T> on List<T> {
  List<T> addToEnd(T element) {
    add(element);
    return this;
  }

  List<T> addToStart(T element) {
    insert(0, element);
    return this;
  }
}


// ---------------------------------------------------------------------------
// asValidator — extension on Function? to use as a FormFieldValidator
// ---------------------------------------------------------------------------
typedef ValidatorFn<T> = String? Function(T?);

extension FunctionValidatorExtension<T> on ValidatorFn<T>? {
  ValidatorFn<T>? asValidator(BuildContext context) => this;
}

// Also on generic Function for FF-generated code that uses `Function?`
extension GenericFunctionValidatorExtension on Function {
  String? Function(String?)? asValidator(BuildContext context) =>
      (value) => this(value) as String?;
}

// ---------------------------------------------------------------------------
// toDynamicWidgetClassDebugData — stub for FlutterFlowDynamicModels
// ---------------------------------------------------------------------------
extension FlutterFlowDynamicModelsDebugExtension<T extends BaseModel>
    on FlutterFlowDynamicModels<T> {
  Map<String, dynamic> toDynamicWidgetClassDebugData() => {};
}


// ---------------------------------------------------------------------------
// serializeParam — stub for FF route serialization
// ---------------------------------------------------------------------------
String? serializeParam(dynamic param, dynamic paramType, {bool isList = false}) =>
    param?.toString();

